package main

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

// ExistsInterface is interface for /exists root endpoint
type ExistsInterface interface { // Post is the handler for POST /exists
	Post(http.ResponseWriter, *http.Request)
}

// ExistsInterfaceRoutes is routing for /exists root endpoint
func ExistsInterfaceRoutes(r *mux.Router, i ExistsInterface) {
	r.HandleFunc("/exists", i.Post).Methods("POST")
}
