package main

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

// InsertInterface is interface for /insert root endpoint
type InsertInterface interface { // Put is the handler for PUT /insert
	Put(http.ResponseWriter, *http.Request)
}

// InsertInterfaceRoutes is routing for /insert root endpoint
func InsertInterfaceRoutes(r *mux.Router, i InsertInterface) {
	r.HandleFunc("/insert", i.Put).Methods("PUT")
}
